### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-stream-app-starters#1]
Looks like the apps are generated with `org.springframework.boot` as the groupId. Shouldn't that be `org.springframework.cloud.stream.app` or something?

The `time` module Java apps have the wrong package - `org.springframework.could.stream.app.time` should be `org.springframework.cloud.stream.app.time`.

**Comment by sobychacko** [comment]
@trisberg Followed the same pattern for other spring cloud apps generated through the initializr. For ex, if you go to start.spring.io, and select eureka, you would get a pom like this:

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.3.RELEASE</version>
		<relativePath/>
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

Although the generated apps are part of the spring-cloud-stream-app-starter repo, each apps are self contained maven modules. Do we want to make it having a different parent than what the other spring cloud apps follow?

**Comment by trisberg** [comment]
Can't we just specify a <groupId> instead of defaulting to the Boot parent groupId

**Comment by sobychacko** [comment]
sure, we can. I will make org.springframework.cloud.stream.app as the parent group id.

**Comment by sobychacko** [comment]
@trisberg new parent groupid/artifactid:
```
<groupId>org.springframework.cloud.stream.app</groupId>
<artifactId>spring-cloud-stream-app-parent</artifactId>
```

The typo in package name for time apps is also fixed.

**Comment by sobychacko** [comment]
@trisberg All the generated apps from Initializr needs to have the spring-boot-parent as this is simply a boot application. They prefer we provide a bom to include all the other dependencies and suggest us not changing the parent that comes as default in any way.
