### ISSUE TITLE
Use commons-logging for all stream apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#11]
As a developer, I'd like to refactor to adapt to `commons-logging` (_instead of slf4j_) as the logging package for all the apps, so it is consistent across the board. 

**Acceptance:**
All stream apps use `commons-logging` as the logging package

**Comment by mbogoevici** [comment]
This is referring to the API used for logging, even if the underlying library is SLF4J. Since the library is actually SLF4J we can standardize any way we want, but we should avoid having a mix of APIs in our application. With SCSt we've aligned with Boot on the use of the Commons Logging API.
