### ISSUE TITLE
Generated apps aren't published to Docker Hub

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-stream-app-starters#116]
There are two CI jobs 

- https://build.spring.io/browse/SCS-APPS 
- https://build.spring.io/browse/SCS-APPSDOCKER. 

The latter has been failing for close to a month and we are not publishing new apps to Docker Hub.

Should these CI jobs be combined into one or should we fix the one that is failing? There seems to be some duplication in what these jobs do.

**Comment by sobychacko** [comment]
This PR fixes this issue: https://github.com/spring-cloud/spring-cloud-stream-app-starters/pull/114
