### ISSUE TITLE
HDFS Source

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-stream-app-starters#117]
As a user, I'd like to have files that are on HDFS as a source so that changes to the files, similar as the file source would be made available through streams.

**Acceptance**:
- Module is available in spring repo
- supported hdfs properties are documented in the reference guide
- On first start the source should read all the documents and stream them

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#31
