### ISSUE TITLE
TCP Source ContentType

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-app-starters#118]
Currently, the TCP source does not add a `contentType` header.

When using, say

```
tcp --outputType=text/plain | ...
```

the conversion to `String` uses the platform charset (e.g. UTF-8) on *nix.

Since the bytes might be in some other charset, it would be useful to be able to specify the charset to use.

**Note: the following requires Spring Integration 4.3...**

As a user, I'd like to be able to configure the tcp source to add a `contentType` header:

```
--addContentType=true
```

which will add the default `contentType` header `application/octet-stream;charset=UTF8`

Further, I would like to be able to specify the header value:

```
--addContentType=true --contentType=application/octet-stream;charset=ISO-8859-1
```

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/tcp#2
