### ISSUE TITLE
Default table name for jdbc sink doesn't match docs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-stream-app-starters#120]
The docs say that the default table name is "stream-name" while the actual name of the table created was "messages".

```
tableName
    String (String, default: <stream name)
```

**Comment by trisberg** [comment]
Looks like we aren't setting `spring.application.name`

```
	@Value("${spring.application.name:messages}")
	private String tableName;
```

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/jdbc#3
