### ISSUE TITLE
JMS source artifacts are not functional

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-app-starters#135]
Currently we generate the JMS source artifacts based on the starter, but we do not include any JMS client libraries, nor do we set up any connection factories. Consequently, the `JmsAutoConfiguration` is not triggered, and the generated artifacts fail to start.

**Comment by cforce** [comment]
Is there a time line for this fix?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/jms#3
