### ISSUE TITLE
Move pmml-processor to a separate repo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#174]
As a developer, I'd like to move `pmml-processor` either to a separate repo or have it decoupled from the build/CI, so it is *not* automatically built and provided as an OOTB application. 

**Reason:**
Since the `jpmml-evaluator` library includes AGPL license, it is advised by the legal to not to have this directly consumable from our distribution. We would leave it to the end users to build and use them either as a standalone stream application or in SCDF. This follows the [similar approach](https://github.com/spring-projects/spring-xd-modules/tree/master/analytics-ml-pmml) that we had in Spring XD.

**Comment by ericbottard** [comment]
I believe it would be better for this to be still part of the starters if possible, but not published (that way, it is still tested and upgraded as other starters are).
Tried to de-activate its publication via the `maven-deploy-plugin` (see 57461a8 but the Artifactory bamboo plugin relies on something else (reverted in 26fc605)).
Need to investigate
