### ISSUE TITLE
Custom Stream app design

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-stream-app-starters#178]
There are 2 ways we can create custom stream app (module) 
1-      Having boot parent - 

```
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.3.RELEASE</version>
</parent>  
```

and then importing org.springframework.cloud.stream.app dependency
1.  Having stream app parent - 
   
   `<parent>
       <groupId>org.springframework.cloud.stream.app</groupId>
       <artifactId>spring-cloud-stream-app-starters</artifactId>
       <version>1.0.0.BUILD-SNAPSHOT</version>
   </parent>`

I am trying to check the advantages of one over other.. also wondering if there is any documentation around this.

**Comment by sobychacko** [comment]
Hi, if you are trying to create a new custom stream app, the best way is to go to start.spring.io, and choose the binder you want and create the artifact. This would create the right spring boot starter parent. Ensure you choose the 1.3.x line of spring boot as thats what will work with spring cloud stream 1.0.x. 

If your intention is to modify an existing app, then go to http://start-scs.cfapps.io/ and choose the right dependency and create the artifact. After that you can modify it to fit your needs. In this case also, you will get the right spring boot parent dependencies.

**Comment by sobychacko** [comment]
Here is where you can find more documentation around app starters: http://docs.spring.io/spring-cloud-stream-app-starters/docs/1.0.2.RELEASE/reference/html/

**Comment by sabbyanandan** [comment]
@sachkk76: could we close this issue?
