### ISSUE TITLE
Key name of spring-configuration-metadata-whitelist.properties

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-stream-app-starters#183]
As per http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.0.0.M4/reference/htmlsingle/ section - 18.1 Whitelisting application properties - 
In description it says key name to be - configuration-properties.classes and example shown just right below uses configuration.classes as a key.  What is the right key name here? 
When I use configuration-properties.classes=x.y.z.XYZSourceProperties or configuration.classes in my custom app. it does not show any custom app properties by app info source:xyzSource or through flo UI
I have spring-boot-starter-parent as parent with version 1.3.5.RELEASE. and spring-cloud-stream-app-dependencies in dependencyManagement

**Comment by markpollack** [comment]
It is with a dash, docs need updating, so thanks.  Are you sure the file is in the resulting jar, e.g. it should sit in a directory like this 

https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/file/spring-cloud-starter-stream-sink-file/src/main/resources/META-INF/spring-configuration-metadata-whitelist.properties

**Comment by markpollack** [comment]
typo fixed in fbd7c1341ed22d35ca4b150ef3552d9557af8921

**Comment by sachkk76** [comment]
Yeah whitelist properties in same place as you pointed out.. and could create jar. but dont see my custom properties getting listed with app info
But one observation if I add dependency of  spring-cloud-starter-stream-source-jms, I could see all properties from org.springframework.boot.autoconfigure.jms.JmsProperties,\  org.springframework.boot.autoconfigure.jms.JmsProperties$Listener,\  org.springframework.cloud.stream.app.jms.source.JmsSourceProperties

**Comment by sachkk76** [comment]
As I said I could see below properties but not my app properties
 spring.jms.jndi-name
spring.jms.pub-sub-domain
jms.subscription-shared
jms.message-selector
jms.destination
jms.session-transacted
jms.subscription-durable
jms.client-id
jms.subscription-name
spring.jms.listener.acknowledge-mode
spring.jms.listener.auto-startup
spring.jms.listener.max-concurrency
spring.jms.listener.concurrency

**Comment by sachkk76** [comment]
One thought - Do I need my custom app to have as stream app parent  instead of spring-boot-starter-parent? 
    <parent>
		<groupId>org.springframework.cloud.stream.app</groupId>
		<artifactId>spring-cloud-stream-app-starters</artifactId>
		<version>1.0.0.BUILD-SNAPSHOT</version>
	</parent>

**Comment by sachkk76** [comment]
So adding org.springframework.cloud.stream.app as parent in pom did show my custom app properties with app info and with flo but stream crashed with below error. This is not the case with spring-boot-starter-parent. With boot parent it works good but dont get access to my properties 

ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
ERR at java.lang.ClassLoader.defineClass1(Native Method)
ERR at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

**Comment by sachkk76** [comment]
So ideally what should be parent pom for dataflow apps, it should be boot-starter or stream-app?

**Comment by ericbottard** [comment]
Which version of boot do you end up using?

**Comment by sachkk76** [comment]
1.3.3.RELEASE

**Comment by sachkk76** [comment]
Even 1.3.5.RELEASE also works.. only thing I cant see my properties

**Comment by sachkk76** [comment]
Just to debug further,  I tried  adding 
configuration-properties.classes=\
  org.springframework.boot.autoconfigure.jms.JmsProperties,\
  org.springframework.boot.autoconfigure.jms.JmsProperties$Listener,\
  org.springframework.cloud.stream.app.jms.source.JmsSourceProperties
  
I could see JmsProperties and JmsProperties$Listener properies but not for JmsSourceProperties
I suspect its do with waht dependecies I am adding to pom 

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.3.RELEASE</version>
	</parent>
	
	<properties>
		<start-class>x.y.z.MyJMSSourceApplication</start-class>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud.stream.app</groupId>
				<artifactId>spring-cloud-stream-app-dependencies</artifactId>
		        <version>1.0.0.BUILD-SNAPSHOT</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement> 

	<dependencies>
       	<dependency>
      		<groupId>org.springframework.cloud</groupId>
      		<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
    	</dependency>		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		 <dependency>
		    <groupId>org.springframework.integration</groupId>
		    <artifactId>spring-integration-jms</artifactId>
		</dependency>
     </dependencies>	

	<build>
		<plugins>
 			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
	</build>

**Comment by sachkk76** [comment]
Any inputs?

**Comment by ericbottard** [comment]
You'll want to make sure that each you list in the properties file appears either
* in a jar embedded in your uber jar (this seems to be ok for the boot ones). If you're doing a _starter_, this should also be true for your own classes
* directly in your uber-jar

You should also make sure that you get a `META-INF/spring-configuration-metadata.json` generated by the boot plugin for `JmsSourceProperties`, visible in your uber jar (either directly in it, or in the embedded jar jar that also contains that class).

Is your code available publicly? This could help diagnosis.

**Comment by sachkk76** [comment]
spring-boot-configuration-processor was missing in pom dependency. cloud resolve this.
The other property "configuration-properties.names" I thought controls what property to expose, but that doesn't seems to be working.

**Comment by ericbottard** [comment]
`spring-boot-configuration-processor` makes boot generate the `spring-configuration-metadata.json` file, which is a necessary (but not sufficient) requirement to solve your problem.

The second part of the equation is to tell dataflow which subset of properties you consider "important" (whitelisting). This is done with `spring-configuration-metadata-whitelist.properties`, which can contain two kinds of entries:
1. `configuration-properties.classes`: whitelist by the name of class(es) containing your properties
2. `configuration-properties.names`: whitelist by the name of the property(ies) itself.

The common case for a custom module that adds new properties is 1)

Hope that makes sense. see [this part of the doc](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-app-whitelisting)

**Comment by sachkk76** [comment]
Thanks @ericbottard !! So not having configuration-properties.names will show all properties of all the classes mentioned as configuration-properties.classes. 
So If I have a property class with 5 properties which is added as a part of configuration-properties.classes and I have mentioned 3 properties name as a part of configuration-properties.names, I should be able to see only those 3 properties right? but I can see all the properties,it does not filter it out.

**Comment by ericbottard** [comment]
If you want only those 3, just use configuration-properties.names. It's
additive.

**Comment by sachkk76** [comment]
Thanks @ericbottard!!
