### ISSUE TITLE
Remove PMML processor coordinates from the bit.ly links

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#193]
As a developer, I'd like to remove `pmml` processor coordinates from all the statically served bit.ly links including the SNAPSHOT/released files - we may have to manually edit the released property files.

**Acceptance:**
- `processor.pmml=maven://org.springframework.cloud.stream.app:pmml-processor-kafka:1.0.2.RELEASE` is removed from all the static files
- PMML processor README is updated with a note stating the license concerns and how to build/register the artifact for use
- Update [PMML sample](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/datascience/species-prediction) to point to the new docs section

**Comment by vruusmann** [comment]
Honestly, I think you're going in the wrong direction here.

As a developer, you need to worry about **_functional dependencies_**. Your documentation (or hyperlinks to the said documentation) cannot be functionally dependent on my AGPLv3 library (unless you've copy&pasted library code to your documentation).

Yet, you have published application code that is functionally dependent on my AGPLv3 library, and released this **_Covered Work_** under AGPLv3 incompatible license - effectively restricting its freedom. As a side note, you cannot solve functional dependency simply by excluding JAR files from the distributable (and ordering end users to download them manually from someplace else such as the Maven Central repository).

**Comment by sabbyanandan** [comment]
@vruusmann: The `pmml-processor` has been move to [spring-cloud-stream-app-starters/pmml](https://github.com/spring-cloud-stream-app-starters/pmml) and the repo in entireity is reclassified with AGPLv3 license. Please refer to the [README](https://github.com/spring-cloud-stream-app-starters/pmml#pmml-processor) for more details.
