### ISSUE TITLE
Upgrade Boot to 1.4.1 in the generated apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#198]

**Comment by markpollack** [comment]
We can not do this until we solve the problem of how to read the whitelist properties.

**Comment by tzolov** [comment]
looks the dependant issue with the whitelist properties has been resolved in 1.1.0 M1?

**Comment by sabbyanandan** [comment]
This is already complete via: https://github.com/spring-cloud-stream-app-starters/core/commit/3c2fdad9acdde2309d6898b8b3461776187a4f0c#diff-600376dffeb79835ede4a0b285078036R27.
