### ISSUE TITLE
groovy-transformer.script with secure url

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-stream-app-starters#199]
I am using groovy-transform-processor and I got my grrovy script at secure location, lets say https://xyz.com/repos/myrepo/groovy-script/myscript.groovy.  My intent is to point out this script to groovy processor app so that it process my data.  Apparently it looks like  since its secure url it needs authentication detail to invoke the script. Is there is way to provide authentication/cert details or it just supports not secure http:// urls?

**Comment by artembilan** [comment]
How about to use URL encoding with `username:password@`?
https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by sachkk76** [comment]
That will be basic authentication which is not enough in my case as it requires certs as I get below error - 

Caused by: org.springframework.integration.transformer.MessageTransformationException: Failed to transform Message; nested exception is org.springframework.messaging.MessageHandlingException: failed to execute script; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at org.springframework.integration.transformer.MessageTransformingHandler.handleRequestMessage(MessageTransformingHandler.java:95) ~[spring-integration-core-4.2.9.RELEASE.jar!/:na]

**Comment by artembilan** [comment]
> failed to execute script; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 

Looks like that is some logic of your script, not a script URL issue.

Anyway that sounds like you have to add certificate for target HTTPS to the trust store of the JVM which calls that script.

**Comment by sachkk76** [comment]
Thanks @artembilan for your inputs.. I am creating dataflow stream on spring cloud dataflow local version having this groovy transform processor and so while starting this local server I gave -Djavax.net.ssl.trustAnchors JVM paramater. I am wondering if I can provide this cert  path to some spring boot property because groovy-transform-processor is essentially boot app

**Comment by artembilan** [comment]
I don't know what is `-Djavax.net.ssl.trustAnchors`, but I'm pretty sure that `-Djavax.net.ssl.trustStore` should work as is. There is no need to worry about any Boot property because that Groovy script is invoked on the same JVM using default SSL context. Just forget that it is Groovy script. At runtime it is just Java, so any JVM options work there as well.
You just should consult with your HTTPS vendor about their trusted certificate to add to your local trsutStore.

**Comment by sabbyanandan** [comment]
@sachkk76: Looks like Artem's response addressed your concern. If you have any other questions, please start a new thread in [StackOverflow](http://stackoverflow.com/questions/tagged/spring-cloud-dataflow).
