### ISSUE TITLE
Reference guide does not include all the docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#204]
The [reference guide](http://docs.spring.io/spring-cloud-stream-app-starters/docs/current-SNAPSHOT/reference/htmlsingle/) is severely outdated. We would have to update the source, processor and sink asciidoc's with relevant README links, so they are included in the generated html fragments.

**Comment by ericbottard** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/210

**Comment by ericbottard** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/211

**Comment by ericbottard** [comment]
Depends https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/212
