### ISSUE TITLE
Fix formatting issues in s3-source docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#205]
As a user, I'm reviewing the currently supported s3-source [options](https://github.com/spring-cloud/spring-cloud-stream-app-starters/tree/master/aws-s3/spring-cloud-starter-stream-source-s3#options;), but the docs are very hard to read, as it is badly formatted.

**Comment by ericbottard** [comment]
Fixed via 2da202b
