### ISSUE TITLE
Add support for "collectionType" in redis-sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#209]
As a developer, I'd like to port `collectionType` support from [XD](http://docs.spring.io/spring-xd/docs/current/reference/html/#redis) to redis-sink. This capability allows pinning the collection type to a variety of data structures and not just `List`, which is the default.

**Comment by markpollack** [comment]
Name of the sink is `redis-pubsub` should change to just redis

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#37
