### ISSUE TITLE
End to end tracing with Spring Cloud Sleuth

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-stream-app-starters#217]
**Goal**: As a user of Spring Streaming Apps I want end to end tracing using Sleuth. 

**Acceptance Criteria**
- [ ] Have a sleuth injector ([like the messaging one](https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument)) 
- [ ] When a stream starts ensure a new span is created and when it's completed stop the span
- [ ] Create a new trace id when no trace id is found in the original message, otherwise carry the found trace id through the system
- [ ] Allow traces/spans to be named. By default use the name of the stream/app
- [ ] Allow each app to add additional meta-data to a span

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#38
