### ISSUE TITLE
Change the default local directory location for FTP source

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#218]
As a developer, I'd like to update the default local [directory location](https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/5675327fc1e44444cf7f5defd1f86acff0e1416a/app-starters-common/app-starters-file-common/src/main/java/org/springframework/cloud/stream/app/file/remote/AbstractRemoteFileSourceProperties.java#L41) from `/home/vcap/tmp/xd/ftp` to `/home/vcap/tmp/scdf/ftp`.

**Acceptance:**
- Default local directory location points to `/home/vcap/tmp/scdf/ftp`
- README/Docs updated to reflect this change

**Comment by ericbottard** [comment]
But do we, really? This couples SCS apps to dataflow, in a way. cc @markfisher

**Comment by sabbyanandan** [comment]
Good point. We could name it more generic then. Perhaps "stream" instead of "scdf"?

**Comment by markfisher** [comment]
We have a similar concern with the File sink: https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/file/spring-cloud-starter-stream-sink-file/src/main/java/org/springframework/cloud/stream/app/file/sink/FileSinkProperties.java#L35

We should avoid "dataflow" in both cases. Perhaps `/tmp/ftp-sink` (and `/tmp/file-sink`) are sufficient for defaults?

**Comment by artembilan** [comment]
`/tmp/sink/ftp`, `/tmp/sink/file`, `/tmp/sink/s3` ?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/ftp#3
