### ISSUE TITLE
how to custom my dataflow without using this project

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-stream-app-starters#231]
i have followed the guide from dataflow 1.0.1 doc,however the custom properties can not show on the page,only using app-starters like @Import(org.springframework.cloud.stream.app.file.sink.FileSinkConfiguration.class) can show the custom properties on the ui page.

**Comment by Jaware** [comment]
![image](https://cloud.githubusercontent.com/assets/3970304/18900742/2060e9b0-8577-11e6-8c14-0d22591b5f93.png)
![image](https://cloud.githubusercontent.com/assets/3970304/18900750/36dd20a0-8577-11e6-8949-663b6e83fbc0.png)
![image](https://cloud.githubusercontent.com/assets/3970304/18900759/4f1cd0c0-8577-11e6-9d26-4eeaf9d6c4aa.png)

**Comment by sabbyanandan** [comment]
Hi, @Jaware: Sorry for the delayed response. Please review the [whitelisting of application properties](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-stream-app-whitelisting) section in the docs for more details.
