### ISSUE TITLE
Split app-starters-common project

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#24]
As a developer, I'd like to split `app-starters-common` project, so that we can pull application specific `@ConfigurationProperties` for related applications instead of inheriting all the (irrelevant) properties from common. 

**Acceptance:**
- `transform` processor should not include `ftp` or `twitterstream` properties
- properties shared by similar apps such as `file-source` and `file-sink` can be inherited by having `file-starter-common` as dependency

**Comment by ilayaperumalg** [comment]
Assigned this to @sobychacko as he is doing the majority of the work on this now.
