### ISSUE TITLE
Explore options to publish generated app artifacts to Bintray

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#245]
As a developer, I'd like to study the best approach to automatically publish generated app artifacts to Bintray, so it can then be automated to synchronize from Bintray to Maven Central.

**Comment by mminella** [comment]
The rest of Spring Cloud doesn't do the Bintray sync at all so why are we pursuing this?

**Comment by sabbyanandan** [comment]
This has been already addressed.
