### ISSUE TITLE
Modify entryPoint to accept JAVA_OPTS environment variable for Docker apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#246]
As a developer, I'd like to modify `<entryPoint>` to accept JAVA_OPTS, so the set of properties are passed over to the generated Docker apps at the build time.

**Comment by ericbottard** [comment]
Should be against https://github.com/spring-cloud/spring-cloud-stream-app-maven-plugin
