### ISSUE TITLE
Create a HAWQ/GPDB CopyManager bulk data transfer sink app

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-stream-app-starters#250]
There is an API for bulk data transfer in Postgres JDBC called CopyManager. I'm wondering if we should investigate creating a sink that makes use of this API, could work well for HAWQ/GPDB without the added complexity of GPFDist. Worth investigating? 
See: https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#40
