### ISSUE TITLE
Move scs-ap-documentation-maven-plugin to new repo

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream-app-starters#252]
https://github.com/spring-cloud/spring-cloud-stream-app-starters/tree/master/spring-cloud-stream-app-documentation-maven-plugin to move into https://github.com/spring-cloud-stream-app-starters

**Comment by markpollack** [comment]
README.md should have a link to point to the latest artifact (much like a project page) so it is easy to ref the latest version.

**Comment by sabbyanandan** [comment]
This is already complete.
