### ISSUE TITLE
Migrate away from using bit.ly links for application releases

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream-app-starters#254]
Need a release train style based after names of famous scientists, first would be Avogadro (Amedeo)  then Bacon (Francis), etc...

Make a new link (on redirect.sping.io) for the application descriptors https://github.com/spring-cloud/spring-cloud-stream-app-starters/tree/master/spring-cloud-stream-app-descriptor

and move away from bit.ly

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#41
