### ISSUE TITLE
Triggertask and Tasklauncher in a stream generate a lot of processes

### ISSUE THREAD

**Issue by pilb** [spring-cloud/spring-cloud-stream-app-starters#259]
Hi,

I need to implement a lot of triggered tasks using dataflow.

I followed documentation here http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_triggertask, here is my command:

stream create --name task-stream --definition 'trigger-task --triggertask.uri="file://path-to-my-task.jar" --trigger.fixed-delay="300" | task-launcher-local' --deploy

I notified that for each stream that i create, about 20 processes for triggertask and tasklauncher are created.

Is there any configuration to avoid this?

Thank you,

Pilb

**Comment by sabbyanandan** [comment]
Hi, @pilb: Thanks for trying Spring Cloud Data Flow! 

The app-starters are common utility applications and as users find they aren't addressing the requirements directly, we recommend extending them. In this case, though, we realize there could be multiple unnecessary processes for every task launch. We will be addressing the concern through #206. In the meantime, you could consider the following options. 

1. Create a custom app that includes both `trigger-task` and `task-launcher` as a single unit. You could then reduce the no. of processes. We will do something like this in #206, but please feel free to submit a PR - we welcome contributions! 😃 
2. Use SCDF's [REST-APIs](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#api-guide-resources-index-links) to directly schedule/launch the task applications via a standalone scheduler or by other means. In this approach, you'd have the tasks just "created" in SCDF and the launching is done outside of it.

**Comment by pilb** [comment]
Thank you for your answer!

By writing processes, i would mean threads.. Sorry for the understanding..

Is there any way to reduce number of threads created by a source or sink for a stream?

Pilb
