### ISSUE TITLE
Move app-starters to individual repos

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#261]
As a developer, I'd like to migrate app-starter projects to its individual repos under [spring-cloud-stream-app-starters](https://github.com/spring-cloud-stream-app-starters) ORG, so it can have independent development and release cadence. 

**Acceptance:**

Following apps needs migrated over with up-to-date README.
- [x] file  
- [x] gemfire  
- [x] gemfire-cq  
- [x] http  
- [x] jdbc  
- [x] jms  
- [x] load-generator  
- [x] loggregator  
- [x] mail  
- [x] mongodb  
- [x] rabbit  
- [x] s3  
- [x] sftp  
- [x] syslog  
- [x] tcp  
- [x] tcp-client  
- [x] time  
- [x] trigger  
- [x] triggertask  
- [x] twitterstream 
- [x] bridge
- [x] filter
- [x] groovy-filter
- [x] groovy-transform
- [x] httpclient
- [x] pmml
- [x] scriptable-transform
- [x] splitter
- [x] tcp-client
- [x] aggregate-counter
- [x] counter
- [x] field-value-counter
- [x] file
- [x] ftp
- [x] gemfire
- [x] gpfdist
- [x] hdfs
- [x] hdfs-dataset
- [x] jdbc
- [x] log
- [x] rabbit
- [x] redis-pubsub
- [x] router
- [x] s3
- [x] sftp
- [x] task-launcher-local
- [x] task-launcher-yarn
- [x] task-launcher-cloudfoundry
- [x] tasklaunchrequest-transform
- [x] tcp
- [x] throughput
- [x] websocket

**Comment by cppwfs** [comment]
Sorry to be a nag, but the TaskLaunchRequestTransform also needs to be migrated.
