### ISSUE TITLE
Task Launcher Local misread URI

### ISSUE THREAD

**Issue by ashwgupt** [spring-cloud/spring-cloud-stream-app-starters#267]
I am raising this issue but unsure if it is a special case or wider...

My stream create command looks like below:-
```
dataflow:>stream create foo --definition "rabbit --rabbit.queues=cloud-stream-source --rabbit.requeue=true --spring.rabbitmq.host=localhost --spring.rabbitmq.port=5672 --spring.cloud.stream.bindings.output.contentType='text/plain' | task-processor --uri=maven://com.example:thumbnail-generator:0.0.1-SNAPSHOT | task-launcher-local-rabbit" --deploy
```
The given maven application thumbnail-generator is installed on my local repo (/Users/apache-maven-3.3.9/.m2/repository/com/example/thumbnail-generator/0.0.1-SNAPSHOT/thumbnail-generator-0.0.1-SNAPSHOT.jar) and should be resolvable, however on every invocation of the task-launcher, below exception appears in the logs:
```
Caused by: java.lang.ClassNotFoundException: aven://com.example:thumbnail-generator:0.0.1-SNAPSHOT
```
The key to notice here is the incorrectly read uri with missing **m** from *maven*.

I could test and confirmed that the first char is always being skipped in the log message.

Is this an issue with the processor passing incorrect uri in the launch request or something task-launcher-local is misreading?

On top of it, why is the launcher failing to fetch the jar file, when present locally? (I've tried by adding an extra **m** to the maven:// uri to find out if that helps but didn't)

Any suggestions please.

**Comment by sabbyanandan** [comment]
Duplicates spring-cloud/spring-cloud-task#240.
