### ISSUE TITLE
Rewrite how to add a new app-starter and generate apps for different binders

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#270]
As a user, I'd like to rewrite the procedure on adding a new app-starter and having it included as part of the build based app generation lifecycle. The [current docs](http://docs.spring.io/spring-cloud-stream-app-starters/docs/1.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#_using_the_artifacts) on this topic is outdated and it needs rewritten.

**Comment by sobychacko** [comment]
docs are updated here: https://github.com/spring-cloud-stream-app-starters/docs/blob/master/spring-cloud-stream-app-starters-docs/src/main/asciidoc/overview.adoc
