### ISSUE TITLE
jdbc.update expression support in source-jdbc starter

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-stream-app-starters#273]
Hi
The common pattern to mark message as `seen` is to  save latest max sequence id from select clause.
It would be great if I could provide `jdbc.update` as expression in form of 
````sql
update bookmark .... value (${Math.max(#payload.columnName)}
````

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/jdbc#4
