### ISSUE TITLE
Http Source ip binding problem

### ISSUE THREAD

**Issue by JavyZheng** [spring-cloud/spring-cloud-stream-app-starters#275]
Hi, I'm using HTTP Source app in my Spring Cloud Data Flow stream running on YARN.

YARN runs in distributed mode.

Each time I deploy the stream, HTTP Source app is deployed to a different YARN slave machine. As a result, my client which sends request to HTTP Source app must change the target IP address each time. 

As the most common use case of HTTP Source is to provide service to a client, a fixed ip address is quite important.

May I ask if there is a method to configure the HTTP Source  to be deployed to the same YARN slave machine?

**Comment by artembilan** [comment]
> May I ask if this is a method to configure the HTTP Source with a fixed ip address?

I wonder if you mean `server.address` options of the Embedded Tomcat: http://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/htmlsingle/#boot-features-customizing-embedded-containers.

Since this HTTP Source application is full Spring Boot application all the properties from the last one is available for your for customization.

**Comment by JavyZheng** [comment]
Hi, @artembilan, thank you for your kind replay and sorry for the misleading. The question would have been:
```
May I ask if there is a method to configure the HTTP Source  to be deployed to the same YARN slave machine?
```
I think the `server.address` option is intended to point out which ip address to bind when multiple network interface appears on one host machine. 

In my case, YARN runs in distributed mode(there are more than 3 slave machines) and the HTTP Source application runs in a YARN container. Each time I deploy the stream on YARN, the HTTP Source container is assigned to one of the slave machines(each slave machine only has on network interface but different slave machine has different ip address). So I want to find a method to make sure the HTTP Source container is deployed to the same slave machine each time.

**Comment by artembilan** [comment]
OK. Thank you for explanation.

Now it is much cleaner, although doesn't say me how to help you. Just because I'm not familiar with YARN :smile: 

And it is really looks like not an HTTP Source problem, but some request for the YARN container.

Maybe @jvalkeal can help you somehow?

**Comment by JavyZheng** [comment]
Yes, @artembilan , actually this is a deployment issue.  But it quite depends on the nature of the application.

This problem only occurs when a **Source Application** works in **server manner**, in which the application need a fixed ip to provide service to the external clients. The HTTP Source falls in this kind of server applications.

Other provided source applications such as the MongoDB Source will not face this problem because it works in **client manner** and just fetches data from external source and put the data to the message broker.

The reason I put the question here is that I think since the HTTP Source is provided, there must be a solution to route the client request to it, otherwise, this source application cannot be put into a real-world stream data flow.

Although it seems that this is not a big issue, I think anyone who wants to put the HTTP Source in a SCDF on YARN stream will face the same problem.

**Comment by artembilan** [comment]
@JavyZheng ,

Sounds like you need a Load Balancer in front of your YARN cluster. And all clients would connect only to the same Load Balancer's IP all the time. 

Actually that is old enough issue for any Web server ran in the cluster.

Also you can consider to use Client side balancer provided with Ribbon: http://cloud.spring.io/spring-cloud-static/Camden.SR2/#spring-cloud-ribbon

**Comment by JavyZheng** [comment]
@artembilan , you mean register(or list) all YARN slave nodes to the load balancer, and each time I deploy the dataflow, let the load balancer to automaticly detect the active node(the node on which the HTTP Source container runs)?

**Comment by artembilan** [comment]
You, know, yes. That is my idea.
At least that is how we have lived before with JBOSS and WebSphere clusters.
For JBOSS we use Apache HTTP server over embedded Tomcats. 
For WAS - there is just built-in Load Balancer.
But I know as our customers used some hard-ware balancers.

I'm not familiar with YARN, but I believe that there should be something similar in Hadoop family...

**Comment by JavyZheng** [comment]
Thanks for your advice. I will have a try on this solution.

**Comment by sabbyanandan** [comment]
@JavyZheng: For any other questions like this, please consider asking in [Stackoverflow](http://stackoverflow.com/questions/tagged/spring-cloud-dataflow). I close this for now.
