### ISSUE TITLE
Property --format doesn't work for time source

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#32]
As a user, I'm using the `time` source and the `--format` property to override the time pattern, but I cannot get it to work. However, it works when I use `--dateFormat` as the property.

**Comment by ericbottard** [comment]
Indeed, according to source code, the correct property is `dateFormat`.
The return type of the getter is not the same as the setter though, which confuses boot metadata generation I guess.
