### ISSUE TITLE
Not able to generate app. Getting NullPointerException

### ISSUE THREAD

**Issue by aamol** [spring-cloud/spring-cloud-stream-app-starters#34]
While trying to generate app using the command in generateApps.sh , PLease let me know if I am missing something

Attached logs with debug and stack trace enabled
[logs.txt](https://github.com/spring-cloud/spring-cloud-stream-app-starters/files/245589/logs.txt)

**Comment by sobychacko** [comment]
Hi @aamol - Can you confirm your maven version? The plugin requires maven 3.3.3 or above. Also, the plugin execution requires JDK 8.

**Comment by aamol** [comment]
Thanks @sobychacko it worked fine with Maven 3.3.+ . I tried 3.0 and 3.2 but not 3.3 :)
