### ISSUE TITLE
Update http://start-scs.cfapps.io/ initializr site for spring-cloud-stream-app-starters M1 release

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream-app-starters#35]
* Default boot version should be the one used for M1
* List all available app-starters
* Remove redis from the binder option
* ~~replace 'search for dependencies' suggested text from `web, security, jpa` to `http-source, file-sink, ...`~~

**Comment by sobychacko** [comment]
All starters are added to start-scs app.
