### ISSUE TITLE
Document how to patch OOTB apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#41]
As a developer, I'd like to document how to patch an OOTB app, so the users can follow the steps to add/update dependencies and/or code fragments as they find fit.

**Acceptance:**
- docs point to http://start-scs.cfapps.io/ and the developer workflow 
- step by step guide to patch an OOTB apps is included in the [reference guide](https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/spring-cloud-stream-app-starters-docs/src/main/asciidoc/overview.adoc)
- [sample](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/streaming/http-to-mysql#12-running-the-sample-locally) should link to the general purpose docs instead of its own

**Comment by trisberg** [comment]
Need the same docs for the task OOTB/starters
