### ISSUE TITLE
Port MQTT as s-c-s source

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#46]
_From @sabbyanandan on November 14, 2015 0:14_

As a developer, I'd like to move _mqtt_ module from XD to s-c-s repo, so I can use it as source to build streaming pipeline. 
**Acceptance:**
- _mqtt_ as source module is available in _spring-cloud-stream-modules_ repo 
- maven repo includes _mqtt_ module with respective group/artifact/version detail

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#71_

**Comment by making** [comment]
I made MQTT source for my [demo](https://github.com/making/spring-cloud-dataflow-playground/tree/master/mqtt).
https://github.com/making/spring-cloud-starter-stream-source-mqtt

**Comment by sabbyanandan** [comment]
@making: That's great! 

As an FYI, we are in the middle of porting over each application to its own repo under [`spring-cloud-stream-app-starters`](https://github.com/spring-cloud-stream-app-starters) ORG. This allows us to release applications independently as opposed to going through a monolith release process. I'll be moving the remaining stories to the consolidated backlog very soon. 

In the meantime, we can create a new repo for mqtt-source and you could contribute this work directly.

**Comment by making** [comment]
Sounds nice! I'll make MQTT sink after that :)

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#8
