### ISSUE TITLE
Port MongoDB as s-c-s sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#49]
_From @sabbyanandan on November 14, 2015 0:14_

As a developer, I'd like to move _mongo_ module from XD to s-c-s repo, so I can use it as sink to build streaming pipeline. 
**Acceptance:**
- _mongo_ as sink module is available in _spring-cloud-stream-modules_ repo 
- maven repo includes _mongo_ module with respective group/artifact/version detail

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#76_

**Comment by sachkk76** [comment]
@sabbyanandan: Do we have mongodb sink OOTB available?

**Comment by sabbyanandan** [comment]
This issue is to specifically add that and it is still open. Until we get to it, perhaps you could try it out and contribute back to the project - we would be happy to review the PR. 😄  

A good reference application would be the existing [`mongo-source`](https://github.com/spring-cloud/spring-cloud-stream-app-starters/tree/master/mongodb/spring-cloud-starter-stream-source-mongodb) and any of OOTB sinks.

**Comment by sachkk76** [comment]
Thanks. I will give a try..

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#10
