### ISSUE TITLE
Port rich-gauge as s-c-s sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#57]
_From @sabbyanandan on November 14, 2015 0:14_

As a developer, I'd like to port _rich-gauge_ module from XD to s-c-s repo, so I can use it as _sink_ module to build streaming pipeline.
**Acceptance:**
- _rich-gauge_ as sink module is available in _spring-cloud-stream-modules_ repo 
- maven repo includes _rich-gauge_ module with respective group/artifact/version

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#94_

**Comment by markpollack** [comment]
There should be code moved into https://github.com/spring-projects/spring-analytics to that SCDF doesn't end up with a dependency on app-starters again

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#18
