### ISSUE TITLE
Logging errors for Kafka with log4j

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-stream-app-starters#7]
The Zookeeper libraries bring in log4j and when I run a Kafka based stream I see these kind of warning messages:

log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkConnection).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by mbogoevici** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-stream/pull/492

**Comment by sabbyanandan** [comment]
This is addressed via spring-cloud/spring-cloud-stream#492.
