### ISSUE TITLE
Add JMS sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#75]
_From @sabbyanandan on February 3, 2016 15:9_

As a user, I'd like to have a `JMS` sink, so I can write the payload to a jms-provider of my choice. 

We would need the following properties: 
- provider
- destinationName
- destinationExpression
- sessionTransacted
- deliveryPersistent*
- pubSubDomain
- priority*
- timeToLive*

_note: \* if any of these properties are set we need to coerce the `explicit-qos-enabled` to be `true`_

**Acceptance:**
- _jms_ as sink module is available in _spring-cloud-stream-modules_ repo 
- maven repo includes _jms_ module with respective group/artifact/version 
- supported properties are documented in the reference guide

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#176_

**Comment by cforce** [comment]
Is there any work alrwady available ..done ?

**Comment by cforce** [comment]
http://stackoverflow.com/questions/35601267/how-to-set-up-spring-cloud-bus-using-activemq

comment from @SpencerGibb
As far as I know ActiveMQ only provides AMQP 1.0 and the rabbit client is 0.9.1, so the answer is "no". If you provided a spring-cloud-stream binder for AMQP 1.0 or JMS or one of the other protocols in ActiveMQ, you might be able to use it that way (in the Brixton release of Spring Cloud). They don't exist out of the box though, so you'd have to write that bit yourself.

**Comment by spencergibb** [comment]
That was @dsyer, not me.

**Comment by dsyer** [comment]
It's also not relevant to this issue.

**Comment by cforce** [comment]
Sorry, i thought its relevant in context of "jms as sink module". Anyway i corrected author of this. Is already any code available for a "jms as sink module"?

**Comment by panga** [comment]
I need a JMS sink to use stream with an existing JMS infrastructure.

After that I think it's possible to create a binder for usage with Cloud Bus.

It will add a great value for leveraging Spring Cloud Stream & Bus capabilities with an existing general purpose JMS infraestructure.

I see there's an empty repo created: https://github.com/spring-cloud/spring-cloud-stream-binder-jms

**Comment by vinayu** [comment]
Any update on this?

**Comment by sabbyanandan** [comment]
The [jms-binder](https://github.com/spring-cloud/spring-cloud-stream-binder-jms) is in the works and once that is formally released, you'd then be able to build stream apps with it as a source or sink. In SCDF, you'd be able to create streams directly communicating via [named channels](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_named_channels), similar to rabbit/kafka. 

That said, we are still evaluating the need for a standalone sink and the decision is pending.

**Comment by cforce** [comment]
Can  i utilize the spring dataflow named channel feature in spring cloud stream using plain old jms messaging ?? I have no idea how my current boot app shall involve into dataflows coming from jms streams..

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/jms#2
