### ISSUE TITLE
Add spring-cloud-stream-modules-analytics to bom

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#78]
_From @markpollack on February 11, 2016 3:25_

Suggested to add this to the bom so dataflow (and presumably other consumers of these modules) would not have to declare this dependency explicity.

Look for this issue name in https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-dependencies/pom.xml as an example. 

Related: https://github.com/spring-cloud/spring-cloud-dataflow/issues/384

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#185_

**Comment by markpollack** [comment]
This issue really belongs in spring-cloud-dataflow....
