### ISSUE TITLE
Add S3 source / sink

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#79]
_From @hvandenb on February 23, 2016 2:11_

As a user, I'd like to have a S3 compatible source/sink, so I can read/write the payload to a S3 bucket.

Poperties:

- S3 bucket url
- file name
- AWS token

Acceptance:

- s3 source/sink module is available in spring-cloud-stream-modules repo
- maven repo includes s3 module with respective group/artifact/version
- supported properties are documented in the reference guide

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#196_

**Comment by artembilan** [comment]
Reopened since `sink` part hasn't been done yet. Plus integration testing "must do" anyway.

**Comment by artembilan** [comment]
Reopened. The `Sink` task hasn't been finished yet
