### ISSUE TITLE
Unable to use double quotes with gpfdist

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#80]
_From @sgulzar-pivotal on March 15, 2016 10:18_

One of the prospects is trying to create a stream and passing the table name in double quotes (Their tables are case sensitive) 

```
file --dir="/home/gpadmin/sppglabtests/" --pattern="testin.csv" --mode="lines" | gpfdist --columnDelimiter="," --dbHost="10.x.x.1" --dbName="spdb" --table="Apple" --mode="INSERT"
```

The stream are failing with the following error:

```
SNAP ERROR sqlTaskScheduler-1 gpfdist.GPFDistMessageHandler - Error in load
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP EXTERNAL TABLE Apple_ext_8cab8bd5_1603_4f28_99e6_2db22583c9ff]; nested exception is org.postgresql.util.PSQLException: ERROR: table "apple_ext_8cab8bd5_1603_4f28_99e6_2db22583c9ff" does not exist
```

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#218_

**Comment by sabbyanandan** [comment]
_From @jvalkeal on March 29, 2016 9:1_

Not really sure what's going on here as I can't reproduce these errors in gpfdist from dataflow(not sure if it'd be any different in XD).

With gpdb/hawq table names are not case sensitive.

**Comment by sgulzar-pivotal** [comment]
We can close this issue Carlos Q and myself has added this feature in the SpringXD 1.3.2.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/gpfdist#5
