### ISSUE TITLE
MongoDB Source

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-stream-app-starters#89]
As a user, I'd like to have a MongoDB source so that changes to documents in MongoDB can be replicated to other systems. 

**Properties:**

- URI: URI to Mongo e.g. mongodb://localhost/
- namespace: the collection to monitor
- tail: boolean indicating if the source needs to be tailed on an ongoing basis

**Acceptance:**

- MongoDB source module is available in spring repo
- supported properties are documented in the reference guide
- On first start the source should read all the documents and stream them
- When tail is specified the source keeps running and monitor the opslog

**Background**

MongoDB provides a feature called [oplog](https://docs.mongodb.com/manual/core/replica-set-oplog/). This feature allows for Async replication of data in a MongoDB instance. However, it can also be used to monitor database changes (new/changes to documents)

Here are some examples of what others have done in this area.
https://www.compose.io/articles/continuously-synchronize-your-mongodb-data-to-elasticsearch/
https://github.com/compose/transporter

**Comment by sabbyanandan** [comment]
This is now addressed via spring-cloud/spring-cloud-stream-app-starters#113.
