### ISSUE TITLE
Cassandra sink insert query regexp validation

### ISSUE THREAD

**Issue by akosratku** [spring-cloud/spring-cloud-stream-app-starters#93]
Hi!

I would like to update counters in cassandra but the current query validation won't let me. My query looks like this: 

`UPDATE views SET view_count = view_count + 1 WHERE id = :id`

Since it doesn't match the [pattern](https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/cassandra/spring-cloud-starter-stream-sink-cassandra/src/main/java/org/springframework/cloud/stream/app/cassandra/sink/CassandraSinkConfiguration.java#L130) my sink won't start up.

Is there a way to loosen the restrictions on the query? I am wondering if the pattern check is even necessary at all?!

Edit: Since cassandra already accepts queryType, the quey parsing could be based on that.

Edit2: I made a quick fix for it so I can progress, I could make it a PR and finalize it if you are interested. [Compare](https://github.com/spring-cloud/spring-cloud-stream-app-starters/compare/master...akosratku:master)

Regards,
Ákos

**Comment by artembilan** [comment]
Hello, @akosratku !

Thank you for the interests of the Spring Cloud Stream and your feedback about this Cassandra Sink issue.

Well, looking at this closely I'd say that we just need to fix that `if`:
```
if (StringUtils.hasText(this.cassandraSinkProperties.getIngestQuery())) {
```
and allow `PayloadToMatrixTransformer` only if the `queryType` is exactly `INSERT`.
On the other hand I'm not sure how your case may work for the `UPDATE` anyway. The `CassandraMessageHandler` has a logic like this:
````java
case INSERT:
		if (this.ingestQuery != null) {
			Assert.isInstanceOf(List.class, payload,
					"to perform 'ingest' the 'payload' must be of 'List<List<?>>' type.");
			List<?> list = (List<?>) payload;
			for (Object o : list) {
				Assert.isInstanceOf(List.class, o,
						"to perform 'ingest' the 'payload' must be of 'List<List<?>>' type.");
			}
			List<List<?>> rows = (List<List<?>>) payload;
				this.cassandraTemplate.ingest(this.ingestQuery, rows, this.writeOptions);
			}
			else {
				if (payload instanceof List) {
					this.cassandraTemplate.insert((List<T>) payload, this.writeOptions);
				}
				else {
					this.cassandraTemplate.insert(payload, this.writeOptions);
				}
			}
			break;
		case UPDATE:
			if (payload instanceof List) {
				this.cassandraTemplate.update((List<T>) payload, this.writeOptions);
			}
			else {
				this.cassandraTemplate.update(payload, this.writeOptions);
			}
			break;
		case DELETE:
````
So, the `ingestQuery` property is used only in case of `INSERT`. The `UPDATE` is fully based on the `payload`.

For your use-case with the `UPDATE ... SET` try to use `statementExpression` property of the Sink.

We don't mind for the PR to fix something, but the fix must be appropriate. In this case we should not allow anything else unless `INSERT` in case of `ingestQuery`.
Although... Exactly that restriction you have just caught with that pattern :smile:

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/cassandra#3
