### ISSUE TITLE
Reconsider the localDir default value

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-app-starters#94]
Right the `AbstractRemoteFileSourceProperties` specifies a `localDir` default value as 

```
private File localDir = new File(System.getProperty("java.io.tmpdir") + "/xd/ftp");
```

This isn't good with the `XD` part, because there is no any XD for this project anyway. (Although such an application can be used in the XD module, too :smile: )

The `FTP` is bad because `AbstractRemoteFileSourceProperties` is a super for the `SFTP` as well. and now for `S3`.

So, the idea is to use something like `${spring.application.name:applicaiton}` instead:

``` java
private String localDir = System.getProperty("java.io.tmpdir") +
            "${spring.application.name:${vcap.application.name:${spring.config.name:application}}}";
...
@NotNull
public File getLocalDir() {
    String localDir = this.localDir;
    if (this.environment != null) {
        localDir = this.environment.resolvePlaceholders(localDir);
    }

    return new File(localDir);
}
```

And thereafter for the target properties:

```
properties.put("spring.application.name", "sftp/source");
```

So, the question: is there some idea really expose the `applicationName` from our apps automatically?
For example when we generate them we can not just left `application.properties` as an empty, but place there a desired "spring.application.name". Or there are some other hooks, e,g, from the Cloud Foundry environment?

On the other hand, if we go some other way for fix this (not `spring.application.name`), what would we choose as a default? Specify the value from each implementors, e.g. from their ctors?

Any other idea?

Thank you!

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#29
